allowBuilds:
   "@parcel/watcher": false
   "@tailwindcss/oxide": false
   esbuild: false
   maplibre-gl: false
   unrs-resolver: false
   vue-demi: false
minimumReleaseAgeExclude:
   - shell-quote@1.8.4
   - esbuild@0.28.1
   - tar@7.5.16
   - vite@7.3.5
   - launch-editor@2.14.1
   - js-yaml@4.1.2
   - "@babel/core@7.29.1"
overrides:
   "@babel/core@<=7.29.0": ^7.29.1
   esbuild@>=0.27.3 <0.28.1: ^0.28.1
   js-yaml@<=4.1.1: ^4.1.2
   launch-editor@<=2.14.0: ^2.14.1
   shell-quote@>=1.1.0 <=1.8.3: ^1.8.4
   tar@<=7.5.15: ^7.5.16
   vite@>=7.0.0 <=7.3.4: ^7.3.5
